FROM edxapp:latest

# Install system dependencies
# Removing the package lists after installation is a good practice
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y dnsutils iputils-ping libsqlite3-dev mongodb vim && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --src ../src -r requirements/edx/testing.txt && \
    pip install --src ../src -r requirements/edx/development.txt

# Update assets skipping collectstatic (not required for development)
RUN NO_PREREQ_INSTALL=1 paver update_assets --settings=fun.docker_build_development --skip-collect
