FROM edxapp:latest

# Install system dependencies
# Removing the package lists after installation is a good practice
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y libsqlite3-dev mongodb && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --src ../src -r requirements/edx/development.txt

# Copy default configurations for development
COPY ./config /config/
